version: '3'
services:
  db:
    image: postgres:10.15
    env_file:
      - .env.development
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - "todo_database:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    networks:
      - gateway

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        make create_admin
        make runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - gateway


volumes:
  todo_database:
    external: true

networks:
  gateway:
    driver: bridge